# # определяет базовый образ
# FROM node
# # если есть гит - клонируем приложение в папку /todo
# RUN git clone -q https://github.com/docker-in-practice/todo.git
# # перехдим в папку /todo 
# WORKDIR /todo
# # устанавливаем зависимости node
# RUN npm install > /dev/null
# # приложение слушает порт 8000
# EXPOSE 8000
# # start process 
# CMD ["npm", "start"]